; Generated by scripts/sync_queries.py from tree-sitter-gsql/queries/textobjects.scm. Do not edit.

; Textobjects for nvim-treesitter-textobjects.

(query_definition) @function.around

(query_definition
  body: (query_body) @function.inside)

(opencypher_query_definition) @function.around

(loading_job_definition) @function.around

(loading_job_definition
  body: (loading_job_body) @function.inside)

(schema_change_job_definition) @function.around

(schema_change_job_definition
  body: (schema_change_body) @function.inside)

(vertex_definition) @class.around

(vertex_definition
  attributes: (vertex_attribute_list) @class.inside)

(edge_definition) @class.around

(edge_definition
  attributes: (edge_attribute_list) @class.inside)

; A parameter or argument with the comma before it, or after it for the
; first (captures of the same name in a match form one range).
(parameter_list
  "," @parameter.around
  .
  (parameter) @parameter.inside @parameter.around)

(parameter_list
  .
  (parameter) @parameter.inside @parameter.around
  .
  ","? @parameter.around)

(argument_list
  "," @parameter.around
  .
  (_) @parameter.inside @parameter.around)

(argument_list
  .
  (_) @parameter.inside @parameter.around
  .
  ","? @parameter.around)

(comment) @comment.around
