; Generated by scripts/sync_queries.py from tree-sitter-gsql/queries/folds.scm. Do not edit.

[
  (query_body)
  (opencypher_body)
  (loading_job_body)
  (schema_change_body)
  (vertex_attribute_list)
  (edge_attribute_list)
  (parameter_list)
  (select_statement)
  (if_statement)
  (else_if_clause)
  (else_clause)
  (case_statement)
  (when_clause)
  (while_statement)
  (foreach_statement)
  (try_statement)
  (exception_handler)
  (accum_clause)
  (post_accum_clause)
  (comment)
] @fold
