; Generated by scripts/sync_queries.py from tree-sitter-gsql/queries/locals.scm. Do not edit.

; Scopes
; ------

[
  (query_definition)
  (interpret_query_statement)
  (select_statement)
  (foreach_statement)
  (delete_statement)
  (update_statement)
  (loading_job_definition)
] @local.scope

; Definitions
; -----------

(parameter
  name: (identifier) @local.definition.parameter)

(variable_declarator
  name: (identifier) @local.definition.var)

(accumulator_declarator
  name: (_) @local.definition.var)

(vertex_set_declaration
  name: (identifier) @local.definition.var)

(assignment_statement
  left: (identifier) @local.definition.var)

(file_declaration
  name: (identifier) @local.definition.var)

(exception_declaration
  name: (identifier) @local.definition.type)

(typedef_statement
  name: (identifier) @local.definition.type)

(virtual_edge_declaration
  name: (identifier) @local.definition.type)

(vertex_pattern
  alias: (identifier) @local.definition.var)

(edge_pattern
  alias: (identifier) @local.definition.var)

(node_pattern
  alias: (identifier) @local.definition.var)

(relationship_detail
  alias: (identifier) @local.definition.var)

(foreach_statement
  variable: (identifier) @local.definition.var)

(foreach_variables
  (identifier) @local.definition.var)

(define_filename_statement
  name: (identifier) @local.definition.var)

(define_header_statement
  name: (identifier) @local.definition.var)

(define_input_line_filter_statement
  name: (identifier) @local.definition.var)

(query_definition
  name: (identifier) @local.definition.function)

(vertex_definition
  name: (identifier) @local.definition.type)

(edge_definition
  name: (identifier) @local.definition.type)

; References
; ----------

(identifier) @local.reference

(global_accumulator) @local.reference

(local_accumulator) @local.reference
