; Generated by scripts/sync_queries.py from tree-sitter-gsql/queries/highlights.scm. Do not edit.

; GSQL highlights, using nvim-treesitter capture names.
;
; Patterns are ordered from general to specific: later patterns take
; precedence (Neovim, Helix and tree-sitter-highlight agree on this).
; scripts/sync_queries.py derives the Helix and Zed variants from this file.

; Identifiers
; -----------

(identifier) @variable

; Keywords
; --------

[
  "ABORT"
  "ACCUM"
  "ADD"
  "ADMIN"
  "ALTER"
  "API"
  "AS"
  "ATTRIBUTE"
  "BEGIN"
  "BOTH"
  "BUILTIN"
  "BY"
  "CLEAR"
  "CONSTANT"
  "CREATE"
  "DATA_SOURCE"
  "DAY"
  "DEFAULT"
  "DEFINE"
  "DELETE"
  "DESCRIPTION"
  "DISCRIMINATOR"
  "DISTINCT"
  "DROP"
  "EDGE"
  "END"
  "EXIT"
  "EXPORT"
  "FILENAME"
  "FOR"
  "FROM"
  "GET"
  "GRANT"
  "GRAPH"
  "GROUP"
  "HAVING"
  "HEADER"
  "HELP"
  "HOUR"
  "IMPORT"
  "INDEX"
  "INPUT_LINE_FILTER"
  "INSERT"
  "INSTALL"
  "INTERPRET"
  "INTERVAL"
  "INTO"
  "JOB"
  "KEY"
  "KEYWORD"
  "LEADING"
  "LIMIT"
  "LOAD"
  "LOADING"
  "LS"
  "METHOD"
  "MINUTE"
  "MONTH"
  "MUTATOR"
  "OBJECT"
  "OFFSET"
  "ON"
  "OPENCYPHER"
  "OPTION"
  "OR"
  "ORDER"
  "OVERWRITE"
  "PACKAGE"
  "PAIR"
  "PASSWORD"
  "PER"
  "PINNED"
  "POST-ACCUM"
  "PRIMARY"
  "PRIMARY_ID"
  "PRINT"
  "PRIVILEGE"
  "PROXY"
  "PUT"
  "QUEUE"
  "QUIT"
  "RANGE"
  "REPLACE"
  "RESUME"
  "REVOKE"
  "ROLE"
  "RUN"
  "SAMPLE"
  "SCHEMA"
  "SCHEMA_CHANGE"
  "SECOND"
  "SECRET"
  "SELECT"
  "SET"
  "SHOW"
  "STORE"
  "SYNTAX"
  "TAG"
  "TAGS"
  "TARGET"
  "TEMP_TABLE"
  "TO"
  "TOKEN"
  "TO_CSV"
  "TRAILING"
  "TYPE"
  "UPDATE"
  "USE"
  "USER"
  "USING"
  "VALUES"
  "VECTOR"
  "VERSION"
  "VERTEX"
  "WHEN"
  "WHERE"
  "WITH"
  "WORKLOAD"
  "YEAR"
] @keyword

[
  "QUERY"
  "FUNCTION"
] @keyword.function

[
  "TYPEDEF"
  "TUPLE"
] @keyword.type

[
  "ALL"
  "CASCADE"
  "COMPRESS"
  "DIRECTED"
  "DISTRIBUTED"
  "GLOBAL"
  "NULLABLE"
  "STATIC"
  "TEMPLATE"
  "UNDIRECTED"
  "VIRTUAL"
  "ASC"
  "DESC"
] @keyword.modifier

[
  "IF"
  "THEN"
  "ELSE"
  "ELSE IF"
  "CASE"
] @keyword.conditional

[
  "WHILE"
  "FOREACH"
  "DO"
  "BREAK"
  "CONTINUE"
] @keyword.repeat

[
  "RETURN"
  "RETURNS"
] @keyword.return

[
  "TRY"
  "EXCEPTION"
  "RAISE"
] @keyword.exception

[
  "AND"
  "NOT"
  "IN"
  "IS"
  "LIKE"
  "ESCAPE"
  "BETWEEN"
  "UNION"
  "INTERSECT"
  "MINUS"
  "EMPTY"
  "NUMERIC"
] @keyword.operator

(binary_expression
  operator: "OR" @keyword.operator)

(break_statement) @keyword.repeat

(continue_statement) @keyword.repeat

; END closes several constructs; color it like the construct it closes.
(if_statement
  "END" @keyword.conditional)

(case_statement
  "END" @keyword.conditional)

(case_expression
  "END" @keyword.conditional)

(while_statement
  "END" @keyword.repeat)

(foreach_statement
  "END" @keyword.repeat)

(try_statement
  "END" @keyword.exception)

(when_clause
  "WHEN" @keyword.conditional)

(exception_handler
  "WHEN" @keyword.exception)

(foreach_statement
  "IN" @keyword.repeat)

(while_statement
  "LIMIT" @keyword.repeat)

; Types
; -----

(primitive_type) @type.builtin

(vertex_type
  "VERTEX" @type.builtin)

(edge_type
  "EDGE" @type.builtin)

(collection_type
  kind: _ @type.builtin)

(accumulator_kind) @type.builtin

(file_type) @type.builtin

(file_declaration
  "FILE" @type.builtin)

(tuple_type
  "TUPLE" @type.builtin)

(type_identifier) @type

(vertex_type
  type: (identifier) @type)

(edge_type
  type: (identifier) @type)

; Schema definitions
; ------------------

(vertex_definition
  name: (identifier) @type)

(edge_definition
  name: (identifier) @type)

(typedef_statement
  name: (identifier) @type)

(virtual_edge_declaration
  name: (identifier) @type)

(graph_definition
  name: (identifier) @type)

(graph_definition
  base: (identifier) @type)

(graph_definition
  member: (identifier) @type)

(graph_definition
  admin: (identifier) @variable)

(tag_expression
  tag: (identifier) @label)

(tag_statement
  name: (identifier) @label)

(tags_clause
  tag: (identifier) @label)

(edge_pair
  from: (identifier) @type)

(edge_pair
  to: (identifier) @type)

(primary_id_definition
  name: (identifier) @property)

(attribute_definition
  name: (identifier) @property)

(primary_key_constraint
  attribute: (identifier) @property)

(discriminator
  (identifier) @property)

(tuple_field
  name: (identifier) @property)

(group_by_field
  name: (identifier) @property)

(sort_key
  name: (identifier) @property)

(option_assignment
  key: (identifier) @property)

(pair
  key: (identifier) @property)

; `{name: "Adam"}` in a pattern names attributes.
(property_map
  (pair
    key: (identifier) @property))

(alter_type_statement
  name: (identifier) @type)

(alter_type_statement
  attribute: (identifier) @property)

(alter_type_statement
  index: (identifier) @variable)

(alter_type_statement
  from: (identifier) @type)

(alter_type_statement
  to: (identifier) @type)

(add_to_graph_statement
  name: (identifier) @type)

(add_to_graph_statement
  graph: (identifier) @type)

(drop_statement
  graph: (identifier) @type)

(alter_graph_statement
  name: (identifier) @type)

(alter_graph_statement
  member: (identifier) @type)

(drop_statement
  kind: [
    "VERTEX"
    "EDGE"
    "TUPLE"
  ]
  name: (identifier) @type)

(drop_statement
  kind: "GRAPH"
  name: (identifier) @type)

(drop_statement
  kind: [
    "QUERY"
    "FUNCTION"
    "JOB"
  ]
  name: (identifier) @function.call)

(drop_statement
  kind: [
    "QUERY"
    "FUNCTION"
  ]
  name: (qualified_identifier
    (identifier) @function.call .))

(name_pattern
  (identifier) @function.call)

(drop_statement
  kind: "PACKAGE"
  name: (_) @type)

(drop_statement
  kind: [
    "USER"
    "ROLE"
    "SECRET"
    "GROUP"
    "TAG"
    "DATA_SOURCE"
  ]
  name: (identifier) @variable)

; Graph, job and query references
; -------------------------------

(for_graph_clause
  graph: (identifier) @type)

(use_statement
  graph: (identifier) @type)

(loading_job_definition
  name: (identifier) @function)

(schema_change_job_definition
  name: (identifier) @function)

(run_job_statement
  job: (identifier) @function.call)

(install_query_statement
  query: (identifier) @function.call)

(install_query_statement
  query: (qualified_identifier
    (identifier) @function.call .))

(run_query_statement
  query: (identifier) @function.call)

(run_query_statement
  query: (qualified_identifier
    (identifier) @function.call .))

(interpret_query_statement
  name: (identifier) @function.call)

(data_source_definition
  name: (identifier) @variable)

(data_source_definition
  type: (identifier) @type)

(package_definition
  name: (_) @type)

(grant_statement
  grantee: (identifier) @variable)

(revoke_statement
  grantee: (identifier) @variable)

(shell_command
  name: (identifier) @variable.special)

(option_flag) @attribute

(command_option
  value: (identifier) @constant)

(file_include) @string.special

; Queries
; -------

(query_definition
  name: (identifier) @function)

(query_definition
  name: (qualified_identifier
    (identifier) @function .))

(opencypher_query_definition
  name: (identifier) @function)

(parameter
  name: (identifier) @variable.parameter)

(api_clause
  version: (identifier) @constant)

(syntax_clause
  version: (identifier) @constant)

; Accumulators
; ------------

[
  (global_accumulator)
  (local_accumulator)
] @property

; Patterns
; --------

(vertex_pattern
  type: (identifier) @type)

(vertex_type_alternation
  (identifier) @type)

(edge_atom
  name: (identifier) @type)

(node_pattern
  type: (identifier) @type)

(relationship_detail
  type: (identifier) @type)

(vertex_set_declaration
  type: (identifier) @type)

(type_wildcard
  type: (identifier) @type)

(any) @constant.builtin

(wildcard) @punctuation.special

; Loading jobs
; ------------

(load_destination
  target: (identifier) @type)

(load_destination
  attribute: (identifier) @property)

(loading_delete_statement
  target: (identifier) @type)

(typed_value
  type: (identifier) @type)

(column_list
  (identifier) @property)

(insert_statement
  target: (identifier) @type)

(insert_columns
  (identifier) @property)

(column_reference) @variable.special

; Exceptions
; ----------

(exception_declaration
  name: (identifier) @type)

(raise_statement
  exception: (identifier) @type)

(exception_handler
  exception: (identifier) @type)

; Functions and members
; ---------------------

(member_expression
  property: (identifier) @property)

(call_expression
  function: (identifier) @function.call)

(call_expression
  function: (member_expression
    property: (identifier) @function.method.call))

((call_expression
  function: (identifier) @function.builtin)
  (#any-of? @function.builtin
    ; math
    "abs" "acos" "asin" "atan" "atan2" "ceil" "cos" "cosh" "cot" "degrees" "exp" "floor" "fmod"
    "ldexp" "log" "log2" "log10" "PI" "pi" "pow" "radians" "rand" "round" "sign" "sin" "sinh" "sqrt"
    "square" "tan" "tanh" "trunc" "float_to_int" "str_to_int" "to_string" "to_int" "to_float"
    "toBoolean" "toFloat" "toInteger"
    ; strings
    "lower" "upper" "trim" "ltrim" "rtrim" "length" "substr" "replace" "ascii" "chr" "difference"
    "instr" "left" "right" "lpad" "rpad" "soundex" "space" "translate" "split" "repeat" "reverse"
    "insert" "find_in_set"
    ; datetime
    "now" "year" "month" "day" "hour" "minute" "second" "week" "datetime_add" "datetime_sub"
    "datetime_diff" "datetime_to_epoch" "epoch_to_datetime" "datetime_format" "to_datetime"
    ; aggregation, lists and collections
    "count" "sum" "min" "max" "avg" "stdev" "stdevp" "isempty" "coalesce" "reset_collection_accum"
    "head" "last" "tail" "size" "range"
    "COUNT" "SUM" "MIN" "MAX" "AVG" "ISEMPTY" "COALESCE" "RESET_COLLECTION_ACCUM" "LOG"
    ; vertices, edges and JSON
    "getvid" "to_vertex" "to_vertex_set" "selectVertex" "SelectVertex" "evaluate" "elementId"
    "parse_json_object" "parse_json_array" "vectorSearch" "tg_similarity_accum"
    "current_roles" "is_granted_to_current_roles"
    ; loading-job token functions
    "gsql_concat" "gsql_to_bool" "gsql_to_uint" "gsql_to_int" "gsql_ts_to_epoch_seconds"
    "gsql_ts_to_epoch_seconds_legacy" "gsql_ts_to_epoch_seconds_signed" "gsql_current_time_epoch"
    "gsql_current_datetime" "gsql_split_by_space" "gsql_upper" "gsql_lower" "gsql_trim" "gsql_ltrim"
    "gsql_rtrim" "gsql_reverse" "gsql_replace" "gsql_regex_replace" "gsql_regex_match"
    "gsql_is_true" "gsql_is_false" "gsql_is_not_empty_string" "gsql_is_not_empty"
    "gsql_token_equal" "gsql_token_ignore_case_equal" "gsql_uuid_v4" "gsql_substring" "gsql_find"
    "gsql_length" "gsql_year" "gsql_month" "gsql_day" "gsql_year_epoch" "gsql_month_epoch"
    "gsql_day_epoch" "concat" "token_len" "flatten" "flatten_json_array" "REDUCE" "reduce"
    "LOADACCUM" "loadaccum"
    ; reducers inside REDUCE(...)
    "add" "and" "or" "overwrite" "ignore_if_exists"))

((identifier) @constant.builtin
  (#any-of? @constant.builtin "GSQL_INT_MAX" "GSQL_INT_MIN" "GSQL_UINT_MAX"))

; Aliases bound in FROM clauses and FOREACH.
(vertex_pattern
  alias: (identifier) @variable)

(edge_pattern
  alias: (identifier) @variable)

(node_pattern
  alias: (identifier) @variable)

(relationship_detail
  alias: (identifier) @variable)

(post_accum_clause
  alias: (identifier) @variable)

(aliased_expression
  alias: (identifier) @property)

; Literals
; --------

(string) @string

(escape_sequence) @string.escape

(integer) @number

(float) @number.float

(boolean) @boolean

(null) @constant.builtin

(define_filename_statement
  path: (string) @string.special)

(file_declaration
  path: (string) @string.special)

; Operators and punctuation
; -------------------------

[
  "="
  "+="
  "=="
  "!="
  "<>"
  "<"
  "<="
  ">"
  ">="
  "+"
  "-"
  "*"
  "/"
  "%"
  "&"
  "|"
  "^"
  "~"
  "<<"
  ">>"
  "->"
  "<-"
  "'"
] @operator

(edge_atom
  direction: _ @operator)

(type_wildcard
  "*" @punctuation.special)

[
  "("
  ")"
  "["
  "]"
  "{"
  "}"
] @punctuation.bracket

(vertex_type
  [
    "<"
    ">"
  ] @punctuation.bracket)

(edge_type
  [
    "<"
    ">"
  ] @punctuation.bracket)

(collection_type
  [
    "<"
    ">"
  ] @punctuation.bracket)

(accumulator_type
  [
    "<"
    ">"
  ] @punctuation.bracket)

(typedef_statement
  [
    "<"
    ">"
  ] @punctuation.bracket)

(tuple_type
  [
    "<"
    ">"
  ] @punctuation.bracket)

[
  ","
  ";"
  "."
  ":"
  ".."
] @punctuation.delimiter

; Comments
; --------

(comment)

(comment) @comment

; Stubs (the reference file of the built-ins)
; -------------------------------------------

(stub_function name: (identifier) @function)
(stub_method name: (identifier) @function.method)
(stub_object name: (identifier) @type)
(stub_object syntax: (stub_syntax) @type)
(stub_declaration (identifier) @constant)
(stub_word) @type.builtin
(stub_signature parameters: (stub_text) @variable.parameter)
(stub_signature returns: (stub_text) @type)
