#!/usr/bin/env python3
"""Generates editor-specific tree-sitter queries from tree-sitter-gsql/queries.

The canonical queries use nvim-treesitter capture names. Patterns are ordered
from general to specific: Neovim, Helix and tree-sitter-highlight (0.25+)
all give later patterns precedence. This script derives:

  editors/neovim/queries/gsql/   verbatim copies
  editors/helix/queries/gsql/    Helix capture names
  editors/zed/languages/gsql/    Zed capture names
  editors/emacs/gsql-ts-mode.el  keyword lists from src/node-types.json

Run without arguments to write the files, or with --check to verify that the
checked-in copies are up to date (used in CI).
"""

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "tree-sitter-gsql" / "queries"

HEADER = "; Generated by scripts/sync_queries.py from tree-sitter-gsql/queries/{name}. Do not edit.\n\n"

HELIX_CAPTURES = {
    "variable.member": "variable.other.member",
    "property": "variable.other.member",
    "module": "namespace",
    "string.escape": "constant.character.escape",
    "character.special": "special",
    "number": "constant.numeric.integer",
    "number.float": "constant.numeric.float",
    "boolean": "constant.builtin.boolean",
    "type.definition": "type",
    "function.call": "function",
    "function.method.call": "function.method",
    "keyword.type": "keyword.storage.type",
    "keyword.modifier": "keyword.storage.modifier",
    "keyword.conditional": "keyword.control.conditional",
    "keyword.repeat": "keyword.control.repeat",
    "keyword.return": "keyword.control.return",
    "keyword.exception": "keyword.control.exception",
}

HELIX_TEXTOBJECTS = {
    "function.outer": "function.around",
    "function.inner": "function.inside",
    "class.outer": "class.around",
    "class.inner": "class.inside",
    "parameter.outer": "parameter.around",
    "parameter.inner": "parameter.inside",
    "comment.outer": "comment.around",
}

ZED_CAPTURES = {
    "variable.member": "property",
    "variable.builtin": "variable.special",
    "module": "type",
    "character.special": "punctuation.special",
    "string.special.path": "string.special",
    "type.definition": "type",
}


def split_patterns(text):
    """Splits a query into (leading comments + pattern) chunks."""
    chunks, i, n = [], 0, len(text)
    pending = ""
    while i < n:
        c = text[i]
        if c.isspace():
            if c == "\n" and pending and not pending.endswith("\n\n"):
                pending += "\n"
            i += 1
            continue
        if c == ";":
            end = text.find("\n", i)
            end = n if end == -1 else end + 1
            pending += text[i:end]
            i = end
            continue
        start = i
        i = skip_expression(text, i)
        # Captures and quantifiers that follow the expression.
        while True:
            m = re.match(r"[ \t]*(@[\w.\-]+|[?*+])", text[i:])
            if not m:
                break
            i += m.end()
        chunks.append((pending, text[start:i]))
        pending = ""
    return chunks, pending


def skip_expression(text, i):
    c = text[i]
    if c == '"':
        i += 1
        while text[i] != '"':
            i += 2 if text[i] == "\\" else 1
        return i + 1
    if c in "([":
        close = ")" if c == "(" else "]"
        depth, i = 0, i
        while True:
            ch = text[i]
            if ch == '"':
                i = skip_expression(text, i)
                continue
            if ch == ";":
                i = text.index("\n", i)
                continue
            if ch in "([":
                depth += 1
            elif ch in ")]":
                depth -= 1
                if depth == 0:
                    return i + 1
            i += 1
    # A bare token such as `_` or a field name.
    m = re.match(r"[^\s()\[\]]+", text[i:])
    return i + m.end()


def rename_captures(text, mapping, drop=()):
    def replace(m):
        name = m.group(1)
        if name in drop:
            return ""
        return "@" + mapping.get(name, name)

    # Rename capture names but not predicate arguments inside strings.
    out, i = [], 0
    for m in re.finditer(r'"(?:\\.|[^"\\])*"|@([\w.\-]+)', text):
        out.append(text[i:m.start()])
        if m.group(0).startswith('"'):
            out.append(m.group(0))
        else:
            out.append(replace(m))
        i = m.end()
    out.append(text[i:])
    result = "".join(out)
    return re.sub(r"[ \t]+\n", "\n", re.sub(r" +(?=\))", "", result))


def drop_unsupported_textobjects(text, supported):
    chunks, _ = split_patterns(text)
    kept = []
    for comments, pattern in chunks:
        captures = set(re.findall(r"@([\w.]+)", pattern))
        if captures and captures <= supported | {"_start", "_end"}:
            kept.append((comments + pattern).strip("\n"))
    return "\n\n".join(kept) + "\n"


EMACS_CONTROL = {"IF", "THEN", "ELSE", "ELSE IF", "END", "CASE", "WHEN", "WHILE", "FOREACH", "DO", "BREAK",
                 "CONTINUE", "RETURN", "RETURNS", "TRY", "RAISE", "EXCEPTION"}
EMACS_OPERATORS = {"AND", "OR", "NOT", "IN", "IS", "LIKE", "ESCAPE", "BETWEEN", "UNION", "INTERSECT", "MINUS"}


def grammar_keywords():
    """Anonymous keyword nodes of the grammar (from src/node-types.json)."""
    import json

    node_types = json.loads((ROOT / "tree-sitter-gsql" / "src" / "node-types.json").read_text())
    names = {n["type"] for n in node_types if not n["named"]}
    return sorted(n for n in names if re.fullmatch(r"[A-Z][A-Z_\- ]*[A-Z]", n))


def emacs_keywords(path):
    """gsql-ts-mode.el with its keyword lists regenerated from the grammar."""
    import textwrap

    keywords = grammar_keywords()

    def defvar(name, words, doc):
        items = " ".join('"%s"' % w for w in words)
        body = "\n".join(textwrap.wrap(items, 72, initial_indent="    ", subsequent_indent="    ", break_on_hyphens=False))
        return f"(defvar {name}\n  '(\n{body})\n  \"{doc}\")\n"

    block = (
        ";; BEGIN GENERATED KEYWORDS (scripts/sync_queries.py)\n"
        + defvar("gsql-ts-mode--control-keywords", [k for k in keywords if k in EMACS_CONTROL],
                 "GSQL control-flow keywords (tree-sitter node names).")
        + "\n"
        + defvar("gsql-ts-mode--operator-keywords", [k for k in keywords if k in EMACS_OPERATORS],
                 "GSQL operator keywords (tree-sitter node names).")
        + "\n"
        + defvar("gsql-ts-mode--keywords",
                 [k for k in keywords if k not in EMACS_CONTROL | EMACS_OPERATORS],
                 "Other GSQL keywords (tree-sitter node names).")
        + ";; END GENERATED KEYWORDS"
    )
    text = path.read_text()
    return re.sub(r";; BEGIN GENERATED KEYWORDS.*?;; END GENERATED KEYWORDS", lambda _: block, text, flags=re.S)


def generated(name, body):
    return HEADER.format(name=name) + body


def outputs():
    files = {}
    read = lambda name: (SOURCE / name).read_text()

    neovim = ROOT / "editors" / "neovim" / "queries" / "gsql"
    for name in ["highlights.scm", "locals.scm", "folds.scm", "indents.scm", "injections.scm", "textobjects.scm"]:
        files[neovim / name] = generated(name, read(name))

    helix = ROOT / "editors" / "helix" / "queries" / "gsql"
    highlights = rename_captures(read("highlights.scm"), HELIX_CAPTURES, drop={"spell"})
    files[helix / "highlights.scm"] = generated("highlights.scm", highlights)
    locals_query = re.sub(r"@local\.definition\.\w+", "@local.definition", read("locals.scm"))
    files[helix / "locals.scm"] = generated("locals.scm", locals_query)
    files[helix / "injections.scm"] = generated("injections.scm", read("injections.scm"))
    textobjects = drop_unsupported_textobjects(read("textobjects.scm"), set(HELIX_TEXTOBJECTS))
    files[helix / "textobjects.scm"] = generated("textobjects.scm", rename_captures(textobjects, HELIX_TEXTOBJECTS))

    zed = ROOT / "editors" / "zed" / "languages" / "gsql"
    files[zed / "highlights.scm"] = generated(
        "highlights.scm", rename_captures(read("highlights.scm"), ZED_CAPTURES, drop={"spell"})
    )
    files[zed / "injections.scm"] = generated("injections.scm", read("injections.scm"))

    emacs = ROOT / "editors" / "emacs" / "gsql-ts-mode.el"
    files[emacs] = emacs_keywords(emacs)
    return files


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="fail if generated files are out of date")
    args = parser.parse_args()
    stale = []
    for path, content in outputs().items():
        current = path.read_text() if path.exists() else None
        if current == content:
            continue
        if args.check:
            stale.append(path.relative_to(ROOT))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
            print(f"wrote {path.relative_to(ROOT)}")
    if stale:
        print("out of date (run scripts/sync_queries.py):", *stale, sep="\n  ")
        sys.exit(1)


if __name__ == "__main__":
    main()
